services:
  free_lunch:
    image: ghcr.io/lunchtimecode/free_lunch
    container_name: free_lunch
    environment:
      - TURSO_DATABASE_URL=":memory:"
      - ROCKET_port=9999
      - ROCKET_address=0.0.0.0
    ports:
      - "9999:9999"